var Constants = {
	PEOPLE_CHANGE_EVENT: 'PEOPLE_CHANGE_EVENT',
	PEOPLE_LOADED: 'PEOPLE_LOADED',
	CURRENT_PERSON_LOADED: 'CURRENT_PERSON_LOADED',
	ORGS_CHANGE_EVENT: 'ORGS_CHANGE_EVENT',
	ORGS_LOADED: 'ORGS_LOADED',
	CURRENT_ORG_LOADED: 'CURRENT_ORG_LOADED',
	CURRENT_ORG_CHANGE_EVENT: 'CURRENT_ORG_CHANGE_EVENT',
	CURRENT_PERSON_CHANGE_EVENT: 'CURRENT_PERSON_CHANGE_EVENT'
};

module.exports = Constants;
